// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'key',
    appId: '1:1016374847819:web:f600e42f23df51d0a560ce',
    messagingSenderId: '1016374847819',
    projectId: 'bmw-flutter',
    authDomain: 'bmw-flutter.firebaseapp.com',
    storageBucket: 'bmw-flutter.appspot.com',
    measurementId: 'G-7TT0VYZ9S5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'key',
    appId: '1:1016374847819:android:dc7621b2577a4d5fa560ce',
    messagingSenderId: '1016374847819',
    projectId: 'bmw-flutter',
    storageBucket: 'bmw-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'key',
    appId: '1:1016374847819:ios:2332e917a3cde788a560ce',
    messagingSenderId: '1016374847819',
    projectId: 'bmw-flutter',
    storageBucket: 'bmw-flutter.appspot.com',
    iosClientId:
        '1016374847819-ukpsmvtp470i9uu33qk2hlkmvaamp98b.apps.googleusercontent.com',
    iosBundleId: 'lk.ceylonedge.bmw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'key',
    appId: '1:1016374847819:ios:7ea87d550663c525a560ce',
    messagingSenderId: '1016374847819',
    projectId: 'bmw-flutter',
    storageBucket: 'bmw-flutter.appspot.com',
    iosClientId:
        '1016374847819-n5tph0k7lamntrneadgoubb1akoti6je.apps.googleusercontent.com',
    iosBundleId: 'lk.ceylonedge.bmw.RunnerTests',
  );
}
